refactoring
EgorLucky/yadplayer-android pull request #1
Opened 2023-08-11 15:02 UTC by EgorLucky

2023-08-12 12:02 UTC, SviatoslavKaptelinin requested changes
🤡🤡🤡🤡🤡

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/main.dart
> +    log(exx.toString());
```
log('Failed to init app:', ex.toString());
```

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/main.dart
>      var exx = ex;
🤡

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/my_home_page/my_home_page.dart
> -      await launch(_loginUrl);
Иф без скобок это 🤡🤡🤡

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/my_home_page/my_home_page.dart
> +    var uri = Uri.parse(_loginUrl);
надо как-то поконкретнее назвать

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/page_manager.dart
> +  Future next() async => _fileCache.next();
nextFile()

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/services/audio_handler.dart
> +
нах тут столько пустых строк🤡

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/services/audio_handler.dart
> +      final newQueue = queue.value..removeAt(index);
что значат джве точки в дартовом?

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/services/audio_handler.dart
> +      final newQueue = queue.value..removeAt(index);
и почему это newQueue? Типа вытащить из очереди что-то, потом в эту же очередь что-то запушить? Як це працюе?

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/services/file_cache.dart
> +
```
  bool Function(File, String) get folderFilter => recursive
      ? (File f, String path) => f.parentFolderPath.startsWith(path)
      : (File f, String path) => f.parentFolderPath == path;
```
Либо вообще через if else перепишите

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/services/file_cache.dart
> +      path = rootPath;
🤡

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/services/file_cache.dart
> +    if(path.isEmpty)
тут как раз можно булево выражение написать вместо ифа

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/services/file_cache.dart
> +      if(isForward){
это жютко выглядит. Сначала `isForward == false` а потом `if(isForward)`
Лучше несколько ифов

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/services/file_cache.dart
> +          .where((f) => folderFilter(f, path))
.filter().map() заменяется на reduce()

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/services/file_cache.dart
> +        _audioHandler.pause();
Я бы смапил просто AudioProcessingState на ButtonState и от половины ифов избавился бы

2023-08-12 12:02 UTC, SviatoslavKaptelinin commented on lib/services/file_cache.dart
> +  void loadParentFolderContent() async {
если в методе проверка, в результате которой он ничего дальше не будет делать, лучше добавить ему префикс `try`

2023-08-27 16:20 UTC, EgorLucky commented on lib/services/audio_handler.dart
> +      final newQueue = queue.value..removeAt(index);
не знаю, я это скопипастил

2023-08-27 16:23 UTC, EgorLucky commented on lib/services/file_cache.dart
> +        _audioHandler.pause();
я это скопипастил и не знаю, как это работает 🤡

2023-08-27 16:25 UTC, EgorLucky commented on lib/services/file_cache.dart
> +
согласен

2023-08-27 18:24 UTC, EgorLucky commented on lib/services/file_cache.dart
> +    if(path.isEmpty)
🤡 тут вам на js

2023-08-30 17:06 UTC, EgorLucky commented on lib/services/file_cache.dart
> +      path = rootPath;
🤡

2023-08-30 17:06 UTC, EgorLucky commented on lib/services/file_cache.dart
> +    if(path.isEmpty)
🤡

2023-08-30 17:06 UTC, EgorLucky commented on lib/services/file_cache.dart
> +          .where((f) => folderFilter(f, path))
🤡

2023-08-30 18:15 UTC, merged